# Numpy Operations

In [1]:
import numpy as np

In [2]:
#Arithmetic operations
a = np.array([10, 20, 30, 40, 50])

In [3]:
#Add
a+2

array([12, 22, 32, 42, 52])

In [4]:
#Sub
a-2

array([ 8, 18, 28, 38, 48])

In [5]:
#Multiplication
a*2

array([ 20,  40,  60,  80, 100])

In [6]:
#Division
a/100

array([0.1, 0.2, 0.3, 0.4, 0.5])

## Comparisons

In [7]:
x = np.array([10, 20, 40, 50, 70])
y = np.array([10, 20, 50, 80, 70])

In [8]:
#Equals
x == y

array([ True,  True, False, False,  True])

In [9]:
#Lesser Than
x < y

array([False, False,  True,  True, False])

In [10]:
#Greater or Equal to
x >= y

array([ True,  True, False, False,  True])

## Logical 

In [11]:
p = np.array([1, 1, 0, 0], dtype=bool)
q = np.array([1, 0, 1, 0], dtype=bool)

In [12]:
#Logical or
np.logical_or(p, q)

array([ True,  True,  True, False])

In [13]:
#Logical and
np.logical_and(p, q)

array([ True, False, False, False])

## Bitwise 

In [25]:
np.bitwise_and([10,],[23])

2

In [15]:
np.bitwise_or([1, 0, 1, 0], [1, 1, 0, 0])

array([1, 1, 1, 0])

In [16]:
bit1 = np.array([1, 2, 3, 4, 5])

In [17]:
bit1 << 1 #Shift Left by one bit

array([ 2,  4,  6,  8, 10])

In [18]:
bit1 >> 1 #Shift Right by one bit

array([0, 1, 1, 2, 2])

## Advance Indexing 

In [19]:
data = np.array([10, 12, 14, 16, 19, 20])

In [20]:
#Get Values > 15
data[ data >15 ]

array([16, 19, 20])

In [21]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [22]:
#First Column values
matrix[:,0]

array([1, 4, 7])

In [23]:
#Second and Third Column values
matrix[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])